const std = @import("std");
const ProtocolSide = @import("wayland_core.zig").ProtocolSide;
const Allocator = std.mem.Allocator;

pub const client_min_id: u32 = 0x00000002;
pub const client_max_id: u32 = 0xfeffffff;
pub const server_min_id: u32 = 0xff000000;
pub const server_max_id: u32 = 0xfffffffe;

const IdAllocator = @This();

next_id: u32,
free_list: std.ArrayList(u32),
min_id: u32,
max_id: u32,

/// An empty allocator for managing client ids.
pub const empty_client = IdAllocator{
    .next_id = client_min_id,
    .free_list = .empty,
    .min_id = client_min_id,
    .max_id = client_max_id,
};

/// An empty allocator for managing server ids.
pub const empty_server = IdAllocator{
    .next_id = server_min_id,
    .free_list = .empty,
    .min_id = server_min_id,
    .max_id = server_max_id,
};

/// Initializes an `IdAllocator` with a free list backed by a stack buffer.
/// This backing buffer cannot grow or be changed during the lifetime of the allocator,
/// and calling any function on the resulting allocator which takes an `std.mem.Allocator`
/// is invalid usage.
pub fn initBounded(side: ProtocolSide, free_list_buffer: []u32) IdAllocator {
    var self = switch (side) {
        .client => empty_client,
        .server => empty_server,
    };
    self.free_list = .initBuffer(free_list_buffer);
    return self;
}

/// Initializes and `IdAllocator` with a free list backed by a growable heap buffer.
/// This `IdAllocator` should be cleaned up with `deinit` when it is no longer needed.
pub fn initCapacity(
    side: ProtocolSide,
    gpa: Allocator,
    free_list_initial_capacity: usize,
) Allocator.Error!IdAllocator {
    var self = switch (side) {
        .client => empty_client,
        .server => empty_server,
    };
    self.free_list = try .initCapacity(gpa, free_list_initial_capacity);
    return self;
}

/// Releases all associated memory, NOT to be used in combination with `initBounded`.
pub fn deinit(self: *IdAllocator, gpa: Allocator) void {
    self.free_list.deinit(gpa);
    self.* = undefined;
}

pub const AllocError = error{
    /// The ID allocator has run out of new IDs within its specified valid range.
    OutOfIds,
};

/// Allocate an ID using the underlying implementation.
/// Returns a valid u32 ID on success.
/// Returns `error.OutOfIds` when the underlying allocator has run out of new IDs.
pub fn alloc(self: *IdAllocator) AllocError!u32 {
    if (self.free_list.pop()) |id| return id;
    if (self.next_id > self.max_id) return error.OutOfIds;
    defer self.next_id += 1;
    return self.next_id;
}

/// Wrapper for allocating an id and casting it to `T`,
/// assuming that `T` is a Wayland interface type generated by the scanner.
pub inline fn create(self: *IdAllocator, comptime T: type) AllocError!T {
    return @enumFromInt(try self.alloc());
}

pub const FreeError = error{
    /// Attempting to free an ID that is outside of the valid range the allocator
    /// was created to handle. For instance, passing a client ID to a server allocaotr,
    /// or passing a server ID to a client allocator.
    InvalidId,
    /// Free list has run out of memory.
    OutOfMemory,
};

/// Free `id` by returning it to the allocator's free list.
/// Can fail with `error.OutOfMemory` if the free list is full and reallocation fails,
/// or `error.InvalidId` when attempting to free an ID that is outside of the allocator's range.
pub fn freeUnbounded(self: *IdAllocator, gpa: Allocator, id: u32) FreeError!void {
    if (id < self.min_id or id > self.max_id)
        return error.InvalidId;

    if (id == self.next_id - 1)
        self.next_id = id
    else
        try self.free_list.append(gpa, id);
}

/// Free `id` by returning it to the allocator's free list.
/// Can fail with `error.OutOfMemory` if the free list is full,
/// or `error.InvalidId` when attempting to free an ID that is outside of the allocator's range.
pub fn freeBounded(self: *IdAllocator, id: u32) FreeError!void {
    if (id < self.min_id or id > self.max_id)
        return error.InvalidId;

    if (id == self.next_id - 1)
        self.next_id = id
    else
        try self.free_list.appendBounded(id);
}

/// Wrapper for calling `freeUnbounded` for `object.getId()`,
/// assuming that `object` is a Wayland object of some type generated by the scanner.
pub inline fn destroyUnbounded(self: *IdAllocator, gpa: Allocator, object: anytype) FreeError!void {
    try self.freeUnbounded(gpa, object.getId());
}

/// Wrapper for calling `freeBounded` for `object.getId()`,
/// assuming that `object` is a Wayland object of some type generated by the scanner.
pub inline fn destroyBounded(self: *IdAllocator, object: anytype) FreeError!void {
    try self.freeBounded(object.getId());
}
