//! An interface similar to std.mem.Allocator for managing Wayland object IDs.

const std = @import("std");
const ProtocolSide = @import("wayland_core.zig").ProtocolSide;

pub const client_min_id: u32 = 0x00000002;
pub const client_max_id: u32 = 0xfeffffff;
pub const server_min_id: u32 = 0xff000000;
pub const server_max_id: u32 = 0xfffffffe;

const IdAllocator = @This();

/// Pointer to backing state.
context: *anyopaque,
vtable: VTable,

pub const VTable = struct {
    alloc: *const fn (*anyopaque) AllocError!u32,
    free: *const fn (*anyopaque, u32) FreeError!void,
};

/// The ID allocator has run out of new IDs within its specified valid range.
pub const AllocError = error{OutOfIds};

pub const FreeError = error{
    /// Attempting to free an ID that is outside of the valid range the allocator
    /// was created to handle. For instance, passing a client ID to a server allocaotr,
    /// or passing a server ID to a client allocator.
    InvalidId,
    /// Free list has run out of memory.
    OutOfMemory,
};

/// Allocate an ID using the underlying implementation.
/// Returns a valid u32 ID on success.
/// Returns `error.OutOfIds` when the underlying allocator has run out of new IDs.
pub inline fn alloc(self: IdAllocator) AllocError!u32 {
    return self.vtable.alloc(self.context);
}

/// Wrapper for allocating an id and casting it to `T`,
/// assuming that `T` is a Wayland interface type generated by the scanner.
pub inline fn createObject(self: IdAllocator, comptime T: type) AllocError!T {
    return @enumFromInt(try self.alloc());
}

/// Free `id` by returning it to the backing allocator.
/// Can fail with `error.OutOfMemory` if the free list of the backing implementation is full,
/// `error.InvalidId` when attempting to free an ID that is outside of its range,
/// or `error.ImplementationSpecific` for any other reason.
pub inline fn free(self: IdAllocator, id: u32) FreeError!void {
    try self.vtable.free(self.context, id);
}

/// A simple ID allocator with a free list backed by a stack buffer.
/// This can be ideal for small programs, or programs with a well-known maximum amount of IDs,
/// but is otherwise not suitable.
pub const Bounded = struct {
    next_id: u32,
    min_id: u32,
    max_id: u32,
    free_list: std.ArrayList(u32),

    /// Initialize an allocator state backed by a buffer, the capacity of which
    /// will be the maximum number of free IDs that can be tracked at any given time.
    /// Freeing any further IDs will result in `error.OutOfMemory`.
    pub fn init(buffer: []u32, protocol_side: ProtocolSide) Bounded {
        return switch (protocol_side) {
            .client => .{
                .next_id = client_min_id,
                .min_id = client_min_id,
                .max_id = client_max_id,
                .free_list = .initBuffer(buffer),
            },
            .server => .{
                .next_id = server_min_id,
                .min_id = server_min_id,
                .max_id = server_max_id,
                .free_list = .initBuffer(buffer),
            },
        };
    }

    /// Get an IdAllocator interface
    pub fn id_allocator(self: *Bounded) IdAllocator {
        return .{
            .context = self,
            .vtable = .{ .alloc = _alloc, .free = _free },
        };
    }

    fn _alloc(context: *anyopaque) IdAllocator.AllocError!u32 {
        var self: *Bounded = @ptrCast(@alignCast(context));
        if (self.free_list.pop()) |id| return id;
        if (self.next_id > self.max_id) return error.OutOfIds;
        defer self.next_id += 1;
        return self.next_id;
    }

    fn _free(context: *anyopaque, id: u32) IdAllocator.FreeError!void {
        var self: *Bounded = @ptrCast(@alignCast(context));

        if (id < self.min_id or id > self.max_id)
            return error.InvalidId;

        if (id == self.next_id - 1)
            self.next_id = id
        else
            try self.free_list.appendBounded(id);
    }
};

/// ID allocator which will never fail to free an ID, as the free list is backed by the heap.
/// For programs that only need a small or well-known number of IDs, see `Bounded`.
pub const Unbounded = struct {
    next_id: u32,
    min_id: u32,
    max_id: u32,
    free_list: std.ArrayList(u32),
    gpa: std.mem.Allocator,

    /// Initialize the id allocator state with space for `initial_capacity` in the free-list.
    pub fn init(
        gpa: std.mem.Allocator,
        protocol_side: ProtocolSide,
        initial_capacity: usize,
    ) std.mem.Allocator.Error!Unbounded {
        return switch (protocol_side) {
            .client => .{
                .next_id = client_min_id,
                .min_id = client_min_id,
                .max_id = client_max_id,
                .free_list = try .initCapacity(gpa, initial_capacity),
                .gpa = gpa,
            },
            .server => .{
                .next_id = server_min_id,
                .min_id = server_min_id,
                .max_id = server_max_id,
                .free_list = try .initCapacity(gpa, initial_capacity),
                .gpa = gpa,
            },
        };
    }

    /// Free the memory for the free-list
    pub fn deinit(self: *Unbounded) void {
        self.free_list.deinit(self.gpa);
    }

    /// Get an IdAllocator interface
    pub fn id_allocator(self: *Unbounded) IdAllocator {
        return .{
            .context = self,
            .vtable = .{ .alloc = _alloc, .free = _free },
        };
    }

    fn _alloc(context: *anyopaque) IdAllocator.AllocError!u32 {
        var self: *Unbounded = @ptrCast(@alignCast(context));
        if (self.free_list.pop()) |id| return id;
        if (self.next_id > self.max_id) return error.OutOfIds;
        defer self.next_id += 1;
        return self.next_id;
    }

    fn _free(context: *anyopaque, id: u32) IdAllocator.FreeError!void {
        var self: *Unbounded = @ptrCast(@alignCast(context));

        if (id < self.min_id or id > self.max_id)
            return error.InvalidId;

        if (id == self.next_id - 1)
            self.next_id = id
        else
            try self.free_list.append(self.gpa, id);
    }
};
